routes:
  - target-url: http://localhost:8080/api/v1
    source-endpoint: /sample-endpoint
    request-timeout: 10
  - target-url: http://localhost:9090/api/v1
    source-endpoint: /sample-url
    request-timeout: 10