name: Project Checks

on:
  - push
  - pull_request

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.7.0
        with:
          java-version: 17
          maven-version: 3.8.3
      - name: Checkstyle
        run: mvn checkstyle:check
      - name: Unit Tests
        run: mvn test
      - name: Publish test coverage
        env:
          CC_TEST_REPORTED_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: src/main/java
        with:
          coverageCommand: mvn jacoco:report
          coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml